### ISSUE TITLE
Presta Shop module

### ISSUE THREAD

**Issue by jvanceCT** [QualityUnit/pap-public#4]
The voucher/coupons in Prestashop are not taken into account when calculating the commissions.

![totals](https://cloud.githubusercontent.com/assets/2922445/6848923/560fb340-d38d-11e4-83b0-e4840f15ae76.JPG)

In the above example - This screen shot is from Prestashop final checkout screen. 
Post affiliate pro paid commission to the affiliate on $99.99 
But should only be paid the commission on $5.00

**Comment by mpullmann** [comment]
@jvanceCT Prestashop plugin is working with discounted price when 'pre product' option is not in use. This is because using discount with per product tracking might result in some problems. The main question is how to work with a discount when the tracking is per product? There is few option and none is perfect:
- we could subtract the discount from one item only (the question is which, if there was more; what if the discount is bigger then an item price; e.g. two items for $19.99 with discount $20 applied: one commission would be $-0.01)
- we could compute a percentage of the coupon value and then apply the percent discount per item (this might cause differences because of number rounding e.g. $5 out of $43 invoice is 11,62790697674419%)
- we could create a separate commission for the discount creating a negative commission, which needs to be enabled in configuration (this is most accurate I would say, but showing negative commissions to affiliates if not the best idea I think)

The solution? The best one is simply not using per product tracking if not necessary - if you have just one campaign, you do not need it. In case you need to track per product items, please contact us and we will custom code it for you.
